
modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="occult"

version="${0.0.1}"

displayName="Occult"

displayURL="http://example.com/"

logoFile="examplemod.png"

credits="DivineAspect, MinerArcana, BGC"

authors="Drizzs, DivineAspect"

description='''

Occult is a Magic Mod!

'''
