
modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MinerArcana/Occult/issues"
[[mods]]
modId="occult"
version="${0.0.1}"
displayName="Occult"
displayURL="https://github.com/MinerArcana/Occult"
logoFile="examplemod.png"
credits="Thanks to: Team RAM(got me started), SkySom(codehelp), DivineAspect(ideas), Snurly(art), Felahliir(art) -- For your contributions and support!"
authors="Drizzs"
description='''
When the world gets between you and the hidden light of magic, you can still call upon it.
'''

